#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libpfm
Version  : 4.11.0
Release  : 5
URL      : http://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz
Source0  : http://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.11.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libpfm-license = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
libpfm4 is a library to help encode events for use with operating system
kernels performance monitoring interfaces. The current version provides support
for the perf_events interface available in upstream Linux kernels since v2.6.31.

%package license
Summary: license components for the libpfm package.
Group: Default

%description license
license components for the libpfm package.


%prep
%setup -q -n libpfm-4.11.0
cd %{_builddir}/libpfm-4.11.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599170800
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1599170800
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libpfm
cp %{_builddir}/libpfm-4.11.0/COPYING %{buildroot}/usr/share/package-licenses/libpfm/cf50044a5e8d62462fece5fa87647aa21228b93f
cp %{_builddir}/libpfm-4.11.0/debian/copyright %{buildroot}/usr/share/package-licenses/libpfm/8b0a4692b7fac3095263d404351506c2a519a525
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libpfm/8b0a4692b7fac3095263d404351506c2a519a525
/usr/share/package-licenses/libpfm/cf50044a5e8d62462fece5fa87647aa21228b93f
