#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libpfm
Version  : 4.10.1
Release  : 2
URL      : http://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.10.1.tar.gz
Source0  : http://sourceforge.net/projects/perfmon2/files/libpfm4/libpfm-4.10.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libpfm-lib
Requires: libpfm-license
BuildRequires : buildreq-distutils3
Patch1: build.patch

%description
libpfm4 is a library to help encode events for use with operating system
kernels performance monitoring interfaces. The current version provides support
for the perf_events interface available in upstream Linux kernels since v2.6.31.

%package dev
Summary: dev components for the libpfm package.
Group: Development
Requires: libpfm-lib
Provides: libpfm-devel

%description dev
dev components for the libpfm package.


%package doc
Summary: doc components for the libpfm package.
Group: Documentation

%description doc
doc components for the libpfm package.


%package lib
Summary: lib components for the libpfm package.
Group: Libraries
Requires: libpfm-license

%description lib
lib components for the libpfm package.


%package license
Summary: license components for the libpfm package.
Group: Default

%description license
license components for the libpfm package.


%prep
%setup -q -n libpfm-4.10.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536633033
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1536633033
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libpfm
cp COPYING %{buildroot}/usr/share/doc/libpfm/COPYING
cp debian/copyright %{buildroot}/usr/share/doc/libpfm/debian_copyright
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/perfmon/perf_event.h
/usr/include/perfmon/pfmlib.h
/usr/include/perfmon/pfmlib_perf_event.h
/usr/lib/libpfm.so
/usr/share/man/man3/libpfm.3
/usr/share/man/man3/libpfm_amd64.3
/usr/share/man/man3/libpfm_amd64_fam10h.3
/usr/share/man/man3/libpfm_amd64_fam15h.3
/usr/share/man/man3/libpfm_amd64_fam16h.3
/usr/share/man/man3/libpfm_amd64_fam17h.3
/usr/share/man/man3/libpfm_amd64_k7.3
/usr/share/man/man3/libpfm_amd64_k8.3
/usr/share/man/man3/libpfm_intel_atom.3
/usr/share/man/man3/libpfm_intel_bdw.3
/usr/share/man/man3/libpfm_intel_bdx_unc_cbo.3
/usr/share/man/man3/libpfm_intel_bdx_unc_ha.3
/usr/share/man/man3/libpfm_intel_bdx_unc_imc.3
/usr/share/man/man3/libpfm_intel_bdx_unc_irp.3
/usr/share/man/man3/libpfm_intel_bdx_unc_pcu.3
/usr/share/man/man3/libpfm_intel_bdx_unc_qpi.3
/usr/share/man/man3/libpfm_intel_bdx_unc_r2pcie.3
/usr/share/man/man3/libpfm_intel_bdx_unc_r3qpi.3
/usr/share/man/man3/libpfm_intel_bdx_unc_sbo.3
/usr/share/man/man3/libpfm_intel_bdx_unc_ubo.3
/usr/share/man/man3/libpfm_intel_core.3
/usr/share/man/man3/libpfm_intel_glm.3
/usr/share/man/man3/libpfm_intel_hsw.3
/usr/share/man/man3/libpfm_intel_hswep_unc_cbo.3
/usr/share/man/man3/libpfm_intel_hswep_unc_ha.3
/usr/share/man/man3/libpfm_intel_hswep_unc_imc.3
/usr/share/man/man3/libpfm_intel_hswep_unc_irp.3
/usr/share/man/man3/libpfm_intel_hswep_unc_pcu.3
/usr/share/man/man3/libpfm_intel_hswep_unc_qpi.3
/usr/share/man/man3/libpfm_intel_hswep_unc_r2pcie.3
/usr/share/man/man3/libpfm_intel_hswep_unc_r3qpi.3
/usr/share/man/man3/libpfm_intel_hswep_unc_sbo.3
/usr/share/man/man3/libpfm_intel_hswep_unc_ubo.3
/usr/share/man/man3/libpfm_intel_ivb.3
/usr/share/man/man3/libpfm_intel_ivb_unc.3
/usr/share/man/man3/libpfm_intel_ivbep_unc_cbo.3
/usr/share/man/man3/libpfm_intel_ivbep_unc_ha.3
/usr/share/man/man3/libpfm_intel_ivbep_unc_imc.3
/usr/share/man/man3/libpfm_intel_ivbep_unc_irp.3
/usr/share/man/man3/libpfm_intel_ivbep_unc_pcu.3
/usr/share/man/man3/libpfm_intel_ivbep_unc_qpi.3
/usr/share/man/man3/libpfm_intel_ivbep_unc_r2pcie.3
/usr/share/man/man3/libpfm_intel_ivbep_unc_r3qpi.3
/usr/share/man/man3/libpfm_intel_ivbep_unc_ubo.3
/usr/share/man/man3/libpfm_intel_knc.3
/usr/share/man/man3/libpfm_intel_knl.3
/usr/share/man/man3/libpfm_intel_knm.3
/usr/share/man/man3/libpfm_intel_nhm.3
/usr/share/man/man3/libpfm_intel_nhm_unc.3
/usr/share/man/man3/libpfm_intel_rapl.3
/usr/share/man/man3/libpfm_intel_skl.3
/usr/share/man/man3/libpfm_intel_skx_unc_cha.3
/usr/share/man/man3/libpfm_intel_skx_unc_imc.3
/usr/share/man/man3/libpfm_intel_skx_unc_irp.3
/usr/share/man/man3/libpfm_intel_skx_unc_m2m.3
/usr/share/man/man3/libpfm_intel_skx_unc_m3upi.3
/usr/share/man/man3/libpfm_intel_skx_unc_pcu.3
/usr/share/man/man3/libpfm_intel_skx_unc_ubo.3
/usr/share/man/man3/libpfm_intel_skx_unc_upi.3
/usr/share/man/man3/libpfm_intel_slm.3
/usr/share/man/man3/libpfm_intel_snb.3
/usr/share/man/man3/libpfm_intel_snb_unc.3
/usr/share/man/man3/libpfm_intel_snbep_unc_cbo.3
/usr/share/man/man3/libpfm_intel_snbep_unc_ha.3
/usr/share/man/man3/libpfm_intel_snbep_unc_imc.3
/usr/share/man/man3/libpfm_intel_snbep_unc_pcu.3
/usr/share/man/man3/libpfm_intel_snbep_unc_qpi.3
/usr/share/man/man3/libpfm_intel_snbep_unc_r2pcie.3
/usr/share/man/man3/libpfm_intel_snbep_unc_r3qpi.3
/usr/share/man/man3/libpfm_intel_snbep_unc_ubo.3
/usr/share/man/man3/libpfm_intel_wsm.3
/usr/share/man/man3/libpfm_intel_wsm_unc.3
/usr/share/man/man3/libpfm_intel_x86_arch.3
/usr/share/man/man3/libpfm_perf_event_raw.3
/usr/share/man/man3/pfm_find_event.3
/usr/share/man/man3/pfm_get_event_attr_info.3
/usr/share/man/man3/pfm_get_event_encoding.3
/usr/share/man/man3/pfm_get_event_info.3
/usr/share/man/man3/pfm_get_event_next.3
/usr/share/man/man3/pfm_get_os_event_encoding.3
/usr/share/man/man3/pfm_get_perf_event_encoding.3
/usr/share/man/man3/pfm_get_pmu_info.3
/usr/share/man/man3/pfm_get_version.3
/usr/share/man/man3/pfm_initialize.3
/usr/share/man/man3/pfm_strerror.3
/usr/share/man/man3/pfm_terminate.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libpfm/*

%files lib
%defattr(-,root,root,-)
/usr/lib/libpfm.so.4
/usr/lib/libpfm.so.4.10.1

%files license
%defattr(-,root,root,-)
/usr/share/doc/libpfm/COPYING
